// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdpvmxzcdjtjkiwylpuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkcHZteHpjZGp0amtpd3lscHV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1MDU0MzQsImV4cCI6MjA4NTA4MTQzNH0.KScboSibmVBzwHoNfQa3m8NtNJfmcITxUyQ1YsojrsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});